python ddpg.py --environment=Swimmer-v1 --epochs=3000 |tee ./experiments_data/Swimmer_ddpg_3.txt &&
python ddpg.py --environment=Walker2d-v1 --epochs=3000 |tee ./experiments_data/Walker2d_ddpg_3.txt &&
python ddpg.py --environment=Ant-v1 --epochs=3000 |tee ./experiments_data/Ant_ddpg_3.txt &&
python ddpg.py --environment=Reacher-v1 --epochs=3000 |tee ./experiments_data/Reacher_ddpg_4.txt &&
python ddpg.py --environment=InvertedDoublePendulum-v1 --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_ddpg_4.txt &&
python ddpg.py --environment=HalfCheetah-v1 --epochs=3000 |tee ./experiments_data/HalfCheetah_ddpg_4.txt &&
python ddpg.py --environment=Hopper-v1 --epochs=3000 |tee ./experiments_data/Hopper_ddpg_4.txt &&
python ddpg.py --environment=Swimmer-v1 --epochs=3000 |tee ./experiments_data/Swimmer_ddpg_4.txt &&
python ddpg.py --environment=Walker2d-v1 --epochs=3000 |tee ./experiments_data/Walker2d_ddpg_4.txt &&
python ddpg.py --environment=Ant-v1 --epochs=3000 |tee ./experiments_data/Ant_ddpg_4.txt &&
python ddpg.py --environment=Reacher-v1 --epochs=3000 |tee ./experiments_data/Reacher_ddpg_5.txt &&
python ddpg.py --environment=InvertedDoublePendulum-v1 --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_ddpg_5.txt &&
python ddpg.py --environment=HalfCheetah-v1 --epochs=3000 |tee ./experiments_data/HalfCheetah_ddpg_5.txt &&
python ddpg.py --environment=Hopper-v1 --epochs=3000 |tee ./experiments_data/Hopper_ddpg_5.txt &&
python ddpg.py --environment=Swimmer-v1 --epochs=3000 |tee ./experiments_data/Swimmer_ddpg_5.txt &&
python ddpg.py --environment=Walker2d-v1 --epochs=3000 |tee ./experiments_data/Walker2d_ddpg_5.txt &&
python ddpg.py --environment=Ant-v1 --epochs=3000 |tee ./experiments_data/Ant_ddpg_5.txt &&
python ddpg.py --environment=Reacher-v1 --epochs=3000 |tee ./experiments_data/Reacher_ddpg_6.txt &&
python ddpg.py --environment=InvertedDoublePendulum-v1 --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_ddpg_6.txt &&
python ddpg.py --environment=HalfCheetah-v1 --epochs=3000 |tee ./experiments_data/HalfCheetah_ddpg_6.txt &&
python ddpg.py --environment=Hopper-v1 --epochs=3000 |tee ./experiments_data/Hopper_ddpg_6.txt &&
python ddpg.py --environment=Swimmer-v1 --epochs=3000 |tee ./experiments_data/Swimmer_ddpg_6.txt &&
python ddpg.py --environment=Walker2d-v1 --epochs=3000 |tee ./experiments_data/Walker2d_ddpg_6.txt &&
python ddpg.py --environment=Ant-v1 --epochs=3000 |tee ./experiments_data/Ant_ddpg_6.txt
