python joint.py --environment=Reacher-v1 --model=gated --epochs=3000 |tee ./experiments_data/Reacher_gated_3.txt &&
python joint.py --environment=InvertedDoublePendulum-v1 --model=gated --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_gated_3.txt &&
python joint.py --environment=HalfCheetah-v1 --model=gated --epochs=3000 |tee ./experiments_data/HalfCheetah_gated_3.txt &&
python joint.py --environment=Hopper-v1 --model=gated --epochs=3000 |tee ./experiments_data/Hopper_gated_3.txt &&
python joint.py --environment=Swimmer-v1 --model=gated --epochs=3000 |tee ./experiments_data/Swimmer_gated_3.txt &&
python joint.py --environment=Walker2d-v1 --model=gated --epochs=3000 |tee ./experiments_data/Walker2d_gated_3.txt &&
python joint.py --environment=Ant-v1 --model=gated --epochs=3000 |tee ./experiments_data/Ant_gated_3.txt &&
python joint.py --environment=Reacher-v1 --model=gated --epochs=3000 |tee ./experiments_data/Reacher_gated_4.txt &&
python joint.py --environment=InvertedDoublePendulum-v1 --model=gated --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_gated_4.txt &&
python joint.py --environment=HalfCheetah-v1 --model=gated --epochs=3000 |tee ./experiments_data/HalfCheetah_gated_4.txt &&
python joint.py --environment=Hopper-v1 --model=gated --epochs=3000 |tee ./experiments_data/Hopper_gated_4.txt &&
python joint.py --environment=Swimmer-v1 --model=gated --epochs=3000 |tee ./experiments_data/Swimmer_gated_4.txt &&
python joint.py --environment=Walker2d-v1 --model=gated --epochs=3000 |tee ./experiments_data/Walker2d_gated_4.txt &&
python joint.py --environment=Ant-v1 --model=gated --epochs=3000 |tee ./experiments_data/Ant_gated_4.txt &&
python joint.py --environment=Reacher-v1 --model=gated --epochs=3000 |tee ./experiments_data/Reacher_gated_5.txt &&
python joint.py --environment=InvertedDoublePendulum-v1 --model=gated --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_gated_5.txt &&
python joint.py --environment=HalfCheetah-v1 --model=gated --epochs=3000 |tee ./experiments_data/HalfCheetah_gated_5.txt &&
python joint.py --environment=Hopper-v1 --model=gated --epochs=3000 |tee ./experiments_data/Hopper_gated_5.txt &&
python joint.py --environment=Swimmer-v1 --model=gated --epochs=3000 |tee ./experiments_data/Swimmer_gated_5.txt &&
python joint.py --environment=Walker2d-v1 --model=gated --epochs=3000 |tee ./experiments_data/Walker2d_gated_5.txt &&
python joint.py --environment=Ant-v1 --model=gated --epochs=3000 |tee ./experiments_data/Ant_gated_5.txt &&
python joint.py --environment=Reacher-v1 --model=gated --epochs=3000 |tee ./experiments_data/Reacher_gated_6.txt &&
python joint.py --environment=InvertedDoublePendulum-v1 --model=gated --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_gated_6.txt &&
python joint.py --environment=HalfCheetah-v1 --model=gated --epochs=3000 |tee ./experiments_data/HalfCheetah_gated_6.txt &&
python joint.py --environment=Hopper-v1 --model=gated --epochs=3000 |tee ./experiments_data/Hopper_gated_6.txt &&
python joint.py --environment=Swimmer-v1 --model=gated --epochs=3000 |tee ./experiments_data/Swimmer_gated_6.txt &&
python joint.py --environment=Walker2d-v1 --model=gated --epochs=3000 |tee ./experiments_data/Walker2d_gated_6.txt &&
python joint.py --environment=Ant-v1 --model=gated --epochs=3000 |tee ./experiments_data/Ant_gated_6.txt
