python joint.py --environment=Reacher-v1 --model=gan --epochs=3000 |tee ./experiments_data/Reacher_gan_3.txt &&
python joint.py --environment=InvertedDoublePendulum-v1 --model=gan --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_gan_3.txt &&
python joint.py --environment=HalfCheetah-v1 --model=gan --epochs=3000 |tee ./experiments_data/HalfCheetah_gan_3.txt &&
python joint.py --environment=Hopper-v1 --model=gan --epochs=3000 |tee ./experiments_data/Hopper_gan_3.txt &&
python joint.py --environment=Swimmer-v1 --model=gan --epochs=3000 |tee ./experiments_data/Swimmer_gan_3.txt &&
python joint.py --environment=Walker2d-v1 --model=gan --epochs=3000 |tee ./experiments_data/Walker2d_gan_3.txt &&
python joint.py --environment=Ant-v1 --model=gan --epochs=3000 |tee ./experiments_data/Ant_gan_3.txt &&
python joint.py --environment=Reacher-v1 --model=gan --epochs=3000 |tee ./experiments_data/Reacher_gan_4.txt &&
python joint.py --environment=InvertedDoublePendulum-v1 --model=gan --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_gan_4.txt &&
python joint.py --environment=HalfCheetah-v1 --model=gan --epochs=3000 |tee ./experiments_data/HalfCheetah_gan_4.txt &&
python joint.py --environment=Hopper-v1 --model=gan --epochs=3000 |tee ./experiments_data/Hopper_gan_4.txt &&
python joint.py --environment=Swimmer-v1 --model=gan --epochs=3000 |tee ./experiments_data/Swimmer_gan_4.txt &&
python joint.py --environment=Walker2d-v1 --model=gan --epochs=3000 |tee ./experiments_data/Walker2d_gan_4.txt &&
python joint.py --environment=Ant-v1 --model=gan --epochs=3000 |tee ./experiments_data/Ant_gan_4.txt &&
python joint.py --environment=Reacher-v1 --model=gan --epochs=3000 |tee ./experiments_data/Reacher_gan_5.txt &&
python joint.py --environment=InvertedDoublePendulum-v1 --model=gan --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_gan_5.txt &&
python joint.py --environment=HalfCheetah-v1 --model=gan --epochs=3000 |tee ./experiments_data/HalfCheetah_gan_5.txt &&
python joint.py --environment=Hopper-v1 --model=gan --epochs=3000 |tee ./experiments_data/Hopper_gan_5.txt &&
python joint.py --environment=Swimmer-v1 --model=gan --epochs=3000 |tee ./experiments_data/Swimmer_gan_5.txt &&
python joint.py --environment=Walker2d-v1 --model=gan --epochs=3000 |tee ./experiments_data/Walker2d_gan_5.txt &&
python joint.py --environment=Ant-v1 --model=gan --epochs=3000 |tee ./experiments_data/Ant_gan_5.txt &&
python joint.py --environment=Reacher-v1 --model=gan --epochs=3000 |tee ./experiments_data/Reacher_gan_6.txt &&
python joint.py --environment=InvertedDoublePendulum-v1 --model=gan --epochs=3000 |tee ./experiments_data/InvertedDoublePendulum_gan_6.txt &&
python joint.py --environment=HalfCheetah-v1 --model=gan --epochs=3000 |tee ./experiments_data/HalfCheetah_gan_6.txt &&
python joint.py --environment=Hopper-v1 --model=gan --epochs=3000 |tee ./experiments_data/Hopper_gan_6.txt &&
python joint.py --environment=Swimmer-v1 --model=gan --epochs=3000 |tee ./experiments_data/Swimmer_gan_6.txt &&
python joint.py --environment=Walker2d-v1 --model=gan --epochs=3000 |tee ./experiments_data/Walker2d_gan_6.txt &&
python joint.py --environment=Ant-v1 --model=gan --epochs=3000 |tee ./experiments_data/Ant_gan_6.txt
