gnome-terminal -e "bash -c 'python joint.py --model=dmlac --time-steps=50000|tee ./mydmlac_pendulum1.txt'"
gnome-terminal -e "bash -c 'python joint.py --model=dmlac --time-steps=50000|tee ./mydmlac_pendulum2.txt'"
gnome-terminal -e "bash -c 'python joint.py --model=dmlac --time-steps=50000|tee ./mydmlac_pendulum3.txt'"
gnome-terminal -e "bash -c 'python joint.py --model=dmlac --time-steps=50000|tee ./mydmlac_pendulum4.txt'"
gnome-terminal -e "bash -c 'python joint.py --model=dmlac --time-steps=50000|tee ./mydmlac_pendulum5.txt'"
