gnome-terminal -e "bash -c 'python joint.py --model=mlp --time-steps=50000|tee ./mymlp_pendulum1.txt && python joint.py --model=gated --time-steps=50000|tee ./mygated_pendulum1.txt'"
gnome-terminal -e "bash -c 'python joint.py --model=mlp --time-steps=50000|tee ./mymlp_pendulum2.txt && python joint.py --model=gated --time-steps=50000|tee ./mygated_pendulum2.txt'"
gnome-terminal -e "bash -c 'python joint.py --model=mlp --time-steps=50000|tee ./mymlp_pendulum3.txt && python joint.py --model=gated --time-steps=50000|tee ./mygated_pendulum3.txt'"
gnome-terminal -e "bash -c 'python joint.py --model=mlp --time-steps=50000|tee ./mymlp_pendulum4.txt && python joint.py --model=gated --time-steps=50000|tee ./mygated_pendulum4.txt'"
gnome-terminal -e "bash -c 'python joint.py --model=mlp --time-steps=50000|tee ./mymlp_pendulum5.txt && python joint.py --model=gated --time-steps=50000|tee ./mygated_pendulum5.txt'"
