#osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_mlp --time-steps=50000 |tee ./dmlac_mlp_1.txt && python joint.py --model=mlp --time-steps=50000 |tee ./mlp_1.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_1.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_1.txt && exit"'
#osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_mlp --time-steps=50000 |tee ./dmlac_mlp_2.txt && python joint.py --model=mlp --time-steps=50000 |tee ./mlp_2.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_2.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_2.txt && exit"'
#osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_mlp --time-steps=50000 |tee ./dmlac_mlp_3.txt && python joint.py --model=mlp --time-steps=50000 |tee ./mlp_3.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_3.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_3.txt && exit"'
#osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_mlp --time-steps=50000 |tee ./dmlac_mlp_4.txt && python joint.py --model=mlp --time-steps=50000 |tee ./mlp_4.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_4.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_4.txt && exit"'
#osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_mlp --time-steps=50000 |tee ./dmlac_mlp_5.txt && python joint.py --model=mlp --time-steps=50000 |tee ./mlp_5.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_5.txt && python ddpg.py --time-steps=50000 |tee ./ddpg_5.txt && exit"'


osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_1.txt && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_6.txt && exit"'
osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_2.txt && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_7.txt && exit"'
osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_3.txt && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_8.txt && exit"'
osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_4.txt && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_9.txt && exit"'
osascript -e 'tell application "Terminal" to do script "cd /Users/trttse/new_drl/prototype8/continuous_action && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_5.txt && python joint.py --model=dmlac_truth --time-steps=50000 |tee ./dmlac_truth_10.txt && exit"'

